### ISSUE TITLE
couldn't run on macOS

### ISSUE THREAD

**Issue by phlinhng** [fiahfy/ico-convert#2] opened 2019-12-23 04:01 UTC
 ~/Downloads  ico-convert                                 1 ↵  11:59:32 
/usr/local/bin/ico-convert: line 1: use strict: command not found
/usr/local/bin/ico-convert: line 2: syntax error near unexpected token `('
/usr/local/bin/ico-convert: line 2: `var __importDefault = (this && this.__importDefault) || function (mod) {'
  ~/Downloads  mv ./Ethereum-ETH-icon.png ./icon.png       2 ↵  11:59:34 
  ~/Downloads  ico-convert icon.png                            12:00:19 
/usr/local/bin/ico-convert: line 1: use strict: command not found
/usr/local/bin/ico-convert: line 2: syntax error near unexpected token `('
/usr/local/bin/ico-convert: line 2: `var __importDefault = (this && this.__importDefault) || function (mod) {'
  ~/Downloads  ico-convert ./icon.png                      2 ↵  12:00:26 
/usr/local/bin/ico-convert: line 1: use strict: command not found
/usr/local/bin/ico-convert: line 2: syntax error near unexpected token `('
/usr/local/bin/ico-convert: line 2: `var __importDefault = (this && this.__importDefault) || function (mod) {'

**Comment by fiahfy** [comment] 2019-12-23 09:37
Thanks for the report.
I know the cause and I will fix it.
This is a temporary solution, but I think it can be done with the following command.
```
node /usr/local/bin/ico-convert icon.png
```

**Comment by fiahfy** [comment] 2019-12-23 14:27
Fixed in v0.0.7

**Closed as completed by fiahfy** 2019-12-23 14:27 UTC
Labels: bug
